// SPDX-License-Identifier: PolyForm-Noncommercial-1.0.0

import { useEffect, useState, useSyncExternalStore, type FormEvent } from 'react'
import { Player, presentationMatches } from './player'
import { GameValue, encodeValue } from './value'
import type { Export, Game, Lobby, Presentation, Room, Slot } from './types'

function form(event: FormEvent<HTMLFormElement>) { event.preventDefault(); return new FormData(event.currentTarget) }
const text = (data: FormData, key: string) => String(data.get(key) ?? '')
const reasons: Record<string, string> = { not_configured: '请先选择游戏内容与参与者席位。', required_seat_missing: '必要席位尚未安排。', consent_required: '参与者尚未同意包清单。', participant_not_ready: '请检查席位、包同意、内容边界与每位参与者的准备状态。', safety_confirmation_required: '参与者尚未确认内容边界。', boundary_conflict: '内容与参与者边界冲突，请更换内容。', model_unavailable: 'AI 参与者暂时不可用，请重新选择。', preparation_changed: '房间配置已变更，请每人重新确认。', service_unavailable: '准备检查暂时不可用。' }

export function App() {
  const [player] = useState(() => new Player())
  const s = useSyncExternalStore(player.subscribe, player.snapshot, player.snapshot)
  const [invite, setInvite] = useState('')
  const [target, setTarget] = useState({ workspace: '', room: '' })
  const [advanced, setAdvanced] = useState(false)
  useEffect(() => {
    const hash = location.hash.slice(1)
    if (/^invite\/[A-Za-z0-9_-]{43}$/.test(hash)) { setInvite(hash.slice(7)); history.replaceState(null, '', location.pathname) }
    else { const match = /^room\/([A-Za-z0-9_.-]+)\/([A-Za-z0-9_.-]+)$/.exec(hash); if (match) setTarget({ workspace: match[1], room: match[2] }) }
    void player.initialize()
  }, [player])
  useEffect(() => {
    let cancelled = false
    let timer: ReturnType<typeof setTimeout>
    const poll = async () => { await player.poll(); if (!cancelled) timer = setTimeout(poll, 2000) }
    timer = setTimeout(poll, 2000)
    return () => { cancelled = true; clearTimeout(timer) }
  }, [player])
  const locked = s.busy || !!s.pending
  const run = (fn: () => Promise<void>) => { void player.run(fn) }
  const account = s.context?.principal?.kind === 'account'
  const guest = s.context?.principal?.kind === 'guest'
  const room = s.room
  const matched = room && s.lobby && s.presentation && presentationMatches(room, s.lobby, s.presentation)
  const name = s.context?.principal?.kind === 'account' ? s.context.principal.display_name : guest ? '受邀访客' : '尚未登录'
  return <main className="app-shell" aria-busy={s.busy}>
    <header className="topbar"><a className="brand" href="#">TRPG <span>Platform</span></a><span>{name}</span><button className="quiet" onClick={() => setAdvanced(!advanced)} aria-expanded={advanced}>高级设置</button></header>
    <section className="hero"><p className="eyebrow">一起入座，开始故事</p><h1>{room ? room.name : '今晚，玩一场。'}</h1><p>{room ? '每位参与者决定自己的边界，服务器持续保存游戏进度。' : '选择游戏与内容，邀请朋友，让 AI 一起参与。'}</p></section>
    <div className="feedback" aria-live="polite">{s.busy && <p role="status">正在与房间同步…</p>}{s.notice && <p role="status">{s.notice}</p>}{s.error && <p className="error" role="alert">{s.error}</p>}{s.pending && <div className="warning"><p>原操作仍待确认，其他提交暂时锁定。</p><button disabled={s.busy} onClick={() => void player.retry()}>查询原操作结果</button></div>}</div>
    {advanced && <section className="panel"><h2>高级设置</h2><p>模型、端点和自带密钥由工作区的服务器管理员配置。普通房间只选择当前可用的 AI 参与者。</p><p>此玩家页面不接收模型密钥。访客可以认领账户，单局身份和权限仍由服务器保留。</p></section>}
    {!s.context && <section className="panel"><h2>连接游戏平台</h2><button disabled={locked} onClick={() => void player.initialize()}>重新获取登录状态</button></section>}
    {s.context?.state === 'anonymous' && <section className="panel"><h2>登录</h2><form onSubmit={e => { const d = form(e); e.currentTarget.reset(); void player.authenticate('/api/v1/auth/login', { login_name: text(d, 'login'), password: text(d, 'password') }) }}><fieldset disabled={locked} className="inline-form"><label>账户名<input name="login" autoComplete="username" required pattern="[a-z][a-z0-9_]{2,31}" /></label><label>密码<input name="password" type="password" autoComplete="current-password" required maxLength={128} /></label><button>登录账户</button></fieldset></form><details><summary>使用部署者提供的注册许可</summary><form onSubmit={e => { const d = form(e); e.currentTarget.reset(); void player.authenticate('/api/v1/auth/register', { login_name: text(d, 'login'), password: text(d, 'password'), display_name: text(d, 'name'), registration_token: text(d, 'grant') }) }}><fieldset disabled={locked}><label>新账户名<input name="login" required pattern="[a-z][a-z0-9_]{2,31}" autoComplete="username" /></label><label>显示名称<input name="name" required maxLength={128} /></label><label>新密码（至少 15 字）<input name="password" type="password" autoComplete="new-password" required minLength={15} maxLength={128} /></label><label>一次性注册许可<input name="grant" type="password" required autoComplete="off" /></label><button>注册账户</button></fieldset></form></details></section>}
    {guest && <section className="panel"><details><summary>认领访客身份</summary><form onSubmit={e => { const d = form(e); e.currentTarget.reset(); const mode = text(d, 'mode'); void player.authenticate('/api/v1/auth/guest/claim', { mode, login_name: text(d, 'login'), password: text(d, 'password'), ...(mode === 'new_account' ? { display_name: text(d, 'name') } : {}) }) }}><fieldset disabled={locked}><label>认领方式<select name="mode"><option value="new_account">创建账户</option><option value="existing_account">使用已有账户</option></select></label><label>账户名<input name="login" autoComplete="username" required pattern="[a-z][a-z0-9_]{2,31}" /></label><label>显示名称（新账户）<input name="name" maxLength={128} /></label><label>密码（新账户至少 15 字）<input name="password" type="password" required maxLength={128} autoComplete="new-password" /></label><button>认领本局身份</button></fieldset></form><p>认领保留本局参与关系；工作区管理与席位权限分别授权。</p></details></section>}
    {(s.context?.state === 'anonymous' || account) && <section className="panel"><h2>通过邀请加入</h2><form onSubmit={e => { const d = form(e); const secret = invite; setInvite(''); run(() => player.join(secret, text(d, 'nickname'))) }}><fieldset disabled={locked} className="inline-form"><label>房间代码或邀请凭证<input name="invite" value={invite} onChange={e => setInvite(e.target.value.trim())} required autoComplete="off" spellCheck={false} /></label>{!account && <label>本局昵称<input name="nickname" required maxLength={80} autoComplete="nickname" /></label>}<button>申请入场</button></fieldset></form><p className="muted">邀请链接会自动填入凭证。邀请只允许申请加入，席位由房主安排。</p></section>}
    {s.admission && <section className="panel"><h2>入场申请</h2><p>{({ pending: '等待房主批准。', approved: '已批准，继续入场。', rejected: '申请已被拒绝。请联系房主。', expired: '申请已过期，请重新获取邀请。' })[s.admission.status]}</p><button disabled={locked} onClick={() => run(() => player.admissionStatus())}>查看申请结果</button></section>}
    {s.context?.state === 'authenticated' && <section className="panel"><h2>继续游戏</h2><form onSubmit={e => { form(e); run(() => player.loadRoom(target.workspace, target.room)) }}><fieldset className="inline-form" disabled={locked}><label>工作区编号<input value={target.workspace} onChange={e => setTarget({ ...target, workspace: e.target.value })} required /></label><label>私人房间编号<input value={target.room} onChange={e => setTarget({ ...target, room: e.target.value })} required /></label><button>打开房间</button></fieldset></form>{room && <p className="muted">房间编号：<code>{room.room_id}</code> · 工作区：<code>{room.workspace_id}</code></p>}</section>}
    {account && !room && <section className="panel"><h2>我的游戏</h2><form onSubmit={e => { const d = form(e); run(() => player.catalog(text(d, 'workspace'))) }}><fieldset disabled={locked} className="inline-form"><label>工作区编号<input name="workspace" required defaultValue={s.workspace} /></label><button>查看可用游戏</button></fieldset></form>{s.workspace && !s.games.length && <p>当前没有可用游戏。请确认工作区授权与已安装内容。</p>}<div className="game-grid">{s.games.map(game => <button key={game.configuration_id} className={'game-card ' + (s.selected?.configuration_id === game.configuration_id ? 'selected' : '')} disabled={locked} onClick={() => run(() => player.select(game))}><strong>{game.title}</strong><span>{game.content_tags.join('、') || '未标注内容标签'}</span><small>{game.configuration_id}</small></button>)}</div>{s.selected && <p>内容提示：{s.selected.content_tags.join('、') || '无标签'} · 安全边界标签：{s.selected.safety_tags.join('、') || '无预设标签'}</p>}{s.presentation && <Packages presentation={s.presentation} />}{s.selected && s.presentation && <form onSubmit={e => { const d = form(e); run(() => player.createRoom(text(d, 'room-name'))) }}><fieldset disabled={locked} className="inline-form"><label>房间名称<input name="room-name" required maxLength={80} /></label><button>创建私人房间</button></fieldset></form>}</section>}
    {room && <section className="room-grid"><section className="panel"><h2>参与者</h2><p>你的房间角色：{room.caller_roles.map(r => ({ owner: '房主', administrator: '管理员', host: '主持人' })[r] ?? r).join('、') || '参与者'}</p><ul>{room.participants.map(p => <li key={p.participant_id}><span>{p.display_name} · {p.kind === 'guest' ? '访客' : '账户'} {p.roles.includes('host') && '· 主持人'}</span>{s.lobby?.can_manage && room.state === 'lobby' && <button className="quiet" disabled={locked} onClick={() => run(() => player.role(p.participant_id, 'host', !p.roles.includes('host')))}>{p.roles.includes('host') ? '撤回主持角色' : '授予主持角色'}</button>}</li>)}</ul><button disabled={locked} onClick={() => run(() => player.refresh())}>刷新房间与准备</button>
      {s.lobby?.can_manage && room.state === 'lobby' && <><h3>邀请朋友</h3><form onSubmit={e => { const d = form(e); run(() => player.invite(d.has('approval'), Number(d.get('minutes')) * 60, Number(d.get('uses')))) }}><fieldset disabled={locked}><label className="check"><input type="checkbox" name="approval" defaultChecked />入场需要批准</label><label>有效分钟<input name="minutes" type="number" defaultValue="60" min="1" max="10080" required /></label><label>可用次数<input name="uses" type="number" defaultValue="4" min="1" max="64" required /></label><button>创建邀请</button></fieldset></form>{s.invitations.map(i => <div className="invitation" key={i.invitation_id}><p>房间代码：<output data-testid="room-code">{i.room_code}</output></p><label>分享链接<input readOnly value={`${location.origin}/#invite/${i.invite_token}`} /></label><p>有效至 {new Date(i.expires_at).toLocaleString()}</p></div>)}{!!s.invitations.length && <button className="quiet" onClick={() => player.dismissInvitations()}>隐藏邀请凭证</button>}{!!s.queue.length && <><h3>等待入场</h3>{s.queue.map(a => <p key={a.admission_id}>{a.display_name}<button disabled={locked} onClick={() => run(() => player.decision(a.admission_id, 'approve'))}>批准入场</button><button className="quiet" disabled={locked} onClick={() => run(() => player.decision(a.admission_id, 'reject'))}>拒绝</button></p>)}</>}</>}
    </section><div className="stack">{room.state === 'lobby' && s.lobby && <>{s.lobby.can_manage && <SeatSetup key={`${room.room_id}/${s.lobby.revision}`} room={room} lobby={s.lobby} games={s.games} presentation={s.presentation} locked={locked} select={g => run(() => player.select(g))} save={(c, slots) => run(() => player.configure(c, slots))} />}<section className="panel"><h2>游戏内容与我的边界</h2>{s.selected && <><h3>{s.selected.title}</h3><p>内容：{s.selected.content_tags.join('、') || '无标签'}</p><p>边界标签：{s.selected.safety_tags.join('、') || '无预设标签'}</p></>}{matched ? <><Packages presentation={s.presentation!} /><ConsentForm key={`${room.room_id}/${s.lobby.revision}/${s.lobby.own_consent.revision}`} lobby={s.lobby} locked={locked} save={own => run(() => player.consent(own))} /></> : <p>请先保存游戏与席位安排，再刷新完整包清单后确认。读取失败或配置不一致时无法准备。</p>}</section><section className="panel"><h2>开局准备</h2><p data-testid="readiness">{s.lobby.readiness.ready ? '所有必要准备已通过。' : '尚未准备完成。'}</p>{s.lobby.readiness.reasons.map(r => <p key={r}>{reasons[r] ?? '请刷新并重新检查准备状态。'}</p>)}{s.lobby.can_manage && <button disabled={locked} onClick={() => run(() => player.launch())}>开始游戏</button>}<p className="muted">开局时再次由服务器检查；任何配置变化都需要每人重新确认。</p></section></>}
      {room.state === 'launched' && <><section className="panel game-panel"><h2>游戏桌</h2>{!s.connection && <><p>连接后恢复你的席位、可见进度与待处理行动。</p><button disabled={locked} onClick={() => run(() => player.connect())}>连接 / 重新连接</button></>}{s.control && <div className={s.control.paused ? 'warning' : 'online'} data-testid="control" data-control-revision={s.control.revision}><p>{s.control.paused ? `游戏暂停：${({ safety: '参与者请求安全暂停', disconnect: '必要参与者连接中断', service_unavailable: '服务暂不可用', none: '等待确认' })[s.control.reason]}` : '游戏进行中'}</p><button className="danger" disabled={s.busy} onClick={() => run(() => player.safety('pause'))}>立即安全暂停</button>{s.control.own_resume_required && <button disabled={s.busy} onClick={() => run(() => player.safety('resume'))}>我已确认边界，继续游戏</button>}</div>}{s.connection && <><p>当前席位：{s.connection.seat_id}</p><div className="actions"><button className="quiet" disabled={locked} onClick={() => run(() => player.disconnect())}>离开游戏连接</button></div></>}{s.snapshot && <><p className="muted">{s.snapshot.ended ? '本局已结束。' : '服务器已保存当前进度。'} 进度版本 {s.snapshot.state_version}</p><div data-testid="game-view"><GameValue value={s.snapshot.view} /></div>{s.snapshot.more && <p>正在补齐允许查看的事件，行动暂时锁定。</p>}<ActionForm locked={locked || s.control?.paused === true || s.snapshot.ended || s.snapshot.more} send={(type, payload) => run(() => player.command(type, payload))} /><details><summary>最近同步的事件</summary>{s.snapshot.events.length ? s.snapshot.events.map(e => <article key={e.sequence}><h3>{e.type}</h3><GameValue value={e.data} /></article>) : <p>暂无新事件。</p>}</details></>}</section><section className="panel"><h2>保存与导出</h2><p>已接受的行动持续保存。导出由服务器按你当前权限筛选。</p><div className="actions"><button disabled={locked} onClick={() => run(() => player.recovery(false))}>查看恢复点</button>{room.caller_roles.includes('host') && <button disabled={locked} onClick={() => run(() => player.recovery(true))}>建立恢复点</button>}</div>{s.point && <p>恢复点版本 {s.point.state_version} · 事件位置 {s.point.event_cursor}</p>}<ExportForm locked={locked} roles={room.caller_roles} submit={(kind, limit) => run(() => player.exportPage(kind, false, limit))} />{s.exported && <section data-testid="export" data-next-cursor={s.exported.next_cursor} data-has-more={s.exported.more}><GameValue value={s.exported.view} /><p>本页 {s.exported.events.length} 条事件{s.exported.more ? '，还有后续页面。' : '，已到末尾。'}</p><button disabled={locked} onClick={() => download(s.exported!)}>下载当前导出页</button>{s.exported.more && <button disabled={locked} onClick={() => run(() => player.exportPage(s.exported!.kind, true))}>读取下一页</button>}</section>}</section></>}
    </div></section>}
    {s.context?.state === 'authenticated' && <footer><button className="quiet" disabled={locked} onClick={() => void player.authenticate('/api/v1/auth/logout', {})}>退出登录</button><p>真人与 AI 使用各自席位的权限。管理房间不授予旁观私密内容的权限。</p></footer>}
  </main>
}

function Packages({ presentation }: { presentation: Presentation }) {
  return <div className="packages"><h3>本局完整包清单</h3>{presentation.packages.map(p => <article key={p.package_id}><strong>{p.title}</strong><p>{p.package_id} · {p.version}</p><p>许可：{p.license}</p><p>声明权限：{p.permissions.join('、') || '无'}</p><details><summary>核对包与授权摘要</summary><p className="digest">{p.artifact_digest}</p><p className="digest">{p.rights_digest}</p></details></article>)}</div>
}
function ConsentForm({ lobby, locked, save }: { lobby: Lobby; locked: boolean; save: (v: { consent: boolean; ready: boolean; safety_confirmed: boolean; boundaries: string[] }) => void }) {
  const own = lobby.own_consent.revision === lobby.revision ? lobby.own_consent : undefined
  return <form onSubmit={e => { const d = form(e); save({ consent: d.has('consent'), ready: d.has('ready'), safety_confirmed: d.has('safety'), boundaries: [...new Set(text(d, 'boundaries').split('\n').map(s => s.trim()).filter(Boolean))] }) }}><fieldset disabled={locked}><label className="check"><input type="checkbox" name="consent" defaultChecked={own?.consent} />我已阅读并同意本局完整包清单</label><label>我的私密内容边界（每行一项，最多 64 项）<textarea name="boundaries" maxLength={5000} defaultValue={own?.boundaries.join('\n') ?? ''} /></label><label className="check"><input type="checkbox" name="safety" defaultChecked={own?.safety_confirmed} />我已确认内容边界，并知道可以随时安全暂停</label><label className="check"><input type="checkbox" name="ready" defaultChecked={own?.ready} />我已准备好</label><button>保存我的同意与准备</button></fieldset></form>
}
function SeatSetup({ room, lobby, games, presentation, locked, select, save }: { room: Room; lobby: Lobby; games: Game[]; presentation?: Presentation; locked: boolean; select: (g: Game) => void; save: (c: string, s: Slot[]) => void }) {
  const [configuration, setConfiguration] = useState(lobby.configuration_id ?? games.find(g => g.game_id === room.game_id)?.configuration_id ?? '')
  const [slots, setSlots] = useState(lobby.slots)
  const game = games.find(g => g.configuration_id === configuration)
  useEffect(() => { if (!configuration) setConfiguration(games.find(g => g.game_id === room.game_id)?.configuration_id ?? '') }, [configuration, games, room.game_id])
  const change = (id: string, choice: string) => { const slot: Slot = choice.startsWith('human:') ? { id, mode: 'human', participant_id: choice.slice(6) } : choice.startsWith('ai:') ? { id, mode: 'ai', model_selection: choice.slice(3) } : { id, mode: 'empty' }; setSlots([...slots.filter(s => s.id !== id), slot]) }
  return <section className="panel"><h2>游戏与席位安排</h2><form onSubmit={e => { form(e); if (game) save(configuration, game.seats.map(s => slots.find(x => x.id === s.id) ?? { id: s.id, mode: 'empty' })) }}><fieldset disabled={locked}><label>游戏内容<select value={configuration} onChange={e => { setConfiguration(e.target.value); setSlots([]); const g = games.find(g => g.configuration_id === e.target.value); if (g) select(g) }}>{games.filter(g => g.game_id === room.game_id).map(g => <option value={g.configuration_id} key={g.configuration_id}>{g.title} · {g.configuration_id}</option>)}</select></label>{game?.seats.map(seat => { const slot = slots.find(s => s.id === seat.id); const value = slot?.mode === 'human' ? 'human:' + slot.participant_id : slot?.mode === 'ai' ? 'ai:' + slot.model_selection : ''; return <label key={seat.id}>席位 {seat.id}{seat.required ? '（必要）' : '（可选）'}<select aria-label={'席位 ' + seat.id} value={value} onChange={e => change(seat.id, e.target.value)}><option value="">暂空</option>{seat.modes.includes('human') && room.participants.map(p => <option value={'human:' + p.participant_id} key={p.participant_id}>{p.display_name} · 真人</option>)}{seat.modes.includes('ai') && presentation?.configuration_id === configuration && presentation.model_selections.filter(m => m.seat_ids.includes(seat.id)).map(m => <option value={'ai:' + m.selection_id} key={m.selection_id} disabled={!m.ready}>{m.label} · AI{!m.ready && '（暂不可用）'}</option>)}</select></label> })}<button disabled={!game}>保存游戏与席位</button></fieldset></form><p className="muted">改动后每位参与者须重新同意并确认准备。AI 选择由服务器检查当前可用性。</p></section>
}
function ActionForm({ locked, send }: { locked: boolean; send: (type: string, payload: ReturnType<typeof encodeValue>) => void }) {
  const [error, setError] = useState('')
  const [fields, setFields] = useState([{ name: '', type: 'text', value: '' }])
  return <form onSubmit={e => { const d = form(e); setError(''); try { const entries = fields.filter(f => f.name !== '').map(f => { if (f.name.length > 256 || f.name.startsWith('cap:')) throw new Error('行动选项名称无效。'); let value: unknown = f.value; if (f.type === 'number') { if (!f.value.trim()) throw new Error('请填写数值。'); value = Number(f.value); if (!Number.isFinite(value)) throw new Error('请填写有限数值。') } if (f.type === 'boolean') value = f.value === 'true'; return [f.name, value] as const }); if (new Set(entries.map(([k]) => k)).size !== entries.length) throw new Error('请勿重复填写同一行动选项。'); send(text(d, 'action'), encodeValue(Object.fromEntries(entries))) } catch (e) { setError(e instanceof Error ? e.message : '请检查行动选项。') } }}><fieldset disabled={locked}><legend>提交行动</legend><p>填写游戏规则提供的行动名称与选项。服务器会检查当前席位、规则和进度。</p><label>行动名称<input name="action" required pattern="[A-Za-z0-9][A-Za-z0-9_.-]{0,127}" /></label>{fields.map((f, i) => <div className="action-field" key={i}><label>选项名称<input aria-label={'选项名称 ' + (i + 1)} value={f.name} onChange={e => setFields(fields.map((x, n) => n === i ? { ...x, name: e.target.value } : x))} /></label><label>选项类型<select aria-label={'选项类型 ' + (i + 1)} value={f.type} onChange={e => setFields(fields.map((x, n) => n === i ? { ...x, type: e.target.value, value: '' } : x))}><option value="text">文字</option><option value="number">数值</option><option value="boolean">是或否</option></select></label><label>选项内容{f.type === 'boolean' ? <select value={f.value} onChange={e => setFields(fields.map((x, n) => n === i ? { ...x, value: e.target.value } : x))}><option value="false">否</option><option value="true">是</option></select> : <input aria-label={'选项内容 ' + (i + 1)} value={f.value} onChange={e => setFields(fields.map((x, n) => n === i ? { ...x, value: e.target.value } : x))} />}</label></div>)}<button className="quiet" type="button" disabled={fields.length >= 32} onClick={() => setFields([...fields, { name: '', type: 'text', value: '' }])}>添加行动选项</button><button>提交行动</button></fieldset>{error && <p role="alert">{error}</p>}</form>
}
function ExportForm({ locked, roles, submit }: { locked: boolean; roles: string[]; submit: (kind: Export['kind'], limit: number) => void }) {
  return <form onSubmit={e => { const d = form(e); submit(text(d, 'kind') as Export['kind'], Number(d.get('export-limit'))) }}><fieldset disabled={locked} className="inline-form"><label>导出范围<select name="kind"><option value="public">公共记录</option><option value="personal">我的记录</option>{roles.includes('host') && <option value="host">主持记录</option>}{(roles.includes('administrator') || roles.includes('owner')) && <option value="administrator">管理备份</option>}</select></label><label>每页事件数<input name="export-limit" type="number" min="1" max="128" defaultValue="128" required /></label><button>生成权限过滤导出</button></fieldset></form>
}
function download(data: Export) { const url = URL.createObjectURL(new Blob([JSON.stringify(data, null, 2)], { type: 'application/json' })); const link = document.createElement('a'); link.href = url; link.download = `game-${data.kind}-${data.next_cursor}.json`; link.click(); URL.revokeObjectURL(url) }
