crate::define_ops_runbook_module!(
    BackupRestoreRunbookCommand,
    append_backup_restore_runbook_event,
    "backup_restore_runbook",
    "OpsBackupRestoreRunbookRecorded",
    crate::OpsRunbookOperation::BackupRestore,
    [
        "backup_manifest",
        "restore_verification",
        "event_store_hash"
    ],
    "evidence/ops/backup-restore-runbook.md"
);
