crate::define_ops_runbook_module!(
    ImplementationPlanCommand,
    append_implementation_plan_event,
    "implementation_plan",
    "OpsImplementationPlanRecorded",
    crate::OpsRunbookOperation::ImplementationPlan,
    [
        "implementation_slice",
        "test_responsibility",
        "handoff_note"
    ],
    "evidence/ops/implementation-plan.md"
);
