crate::define_ops_runbook_module!(
    ImplementationPlanCommand,
    ImplementationPlanService,
    ImplementationPlanRepository,
    ImplementationPlanError,
    append_implementation_plan_event,
    "CODEX-0921-11-OPS-MIGRATION-7457f82a14",
    "implementation_plan",
    "OpsImplementationPlanRecorded",
    crate::OpsRunbookOperation::ImplementationPlan,
    [
        "implementation_slice",
        "test_responsibility",
        "handoff_note"
    ],
    "evidence/batches/BATCH-042/implementation-plan.md"
);
