crate::define_ops_runbook_module!(
    UpgradeBackupReplayRunbooksCommand,
    append_upgrade_backup_replay_runbooks_event,
    "upgrade_backup_replay_runbooks",
    "OpsUpgradeBackupReplayRunbooksRecorded",
    crate::OpsRunbookOperation::UpgradeBackupReplay,
    [
        "backup_manifest",
        "restore_verification",
        "projection_replay",
        "incident_response"
    ],
    "evidence/ops/upgrade-backup-replay-runbooks.md"
);
