crate::define_ops_runbook_module!(
    UpgradeBackupReplayRunbooksCommand,
    UpgradeBackupReplayRunbooksService,
    UpgradeBackupReplayRunbooksRepository,
    UpgradeBackupReplayRunbooksError,
    append_upgrade_backup_replay_runbooks_event,
    "CODEX-0927-11-OPS-MIGRATION-5a238036dd",
    "upgrade_backup_replay_runbooks",
    "OpsUpgradeBackupReplayRunbooksRecorded",
    crate::OpsRunbookOperation::UpgradeBackupReplay,
    [
        "backup_manifest",
        "restore_verification",
        "projection_replay",
        "incident_response"
    ],
    "evidence/batches/BATCH-042/upgrade-backup-replay-runbooks.md"
);
