crate::define_data_event_module!(
    EventSourcingCqrsCommand,
    EventSourcingCqrsOperation,
    append_event_sourcing_cqrs_event,
    "adr_0002_event_sourcing_cqrs_event_sourcing_cqrs",
    "EventSourcingCqrsDecisionRecorded",
    "data_eventing.adr_0002_event_sourcing_cqrs.event_schema",
    crate::DataEventOperation::ArchitectureDecisionRecord,
    ["architecture_decision_index"]
);
