crate::define_data_event_module!(
    EventSchemaIndexCommand,
    EventSchemaIndexOperation,
    append_event_schema_index_event,
    "event_schema_index",
    "EventSchemaIndexEventRecorded",
    "data_eventing.event_schema_index.event_schema",
    crate::DataEventOperation::SchemaRegister,
    ["event_schema_catalog"]
);
