use rand_core::{OsRng, RngCore};

use crate::{KernelResult, TrpgError};

/// Opaque evidence for a percentile roll produced by the server OS CSPRNG.
/// The fields are intentionally private and the type is not deserializable.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct ServerPercentileRoll {
    roll_id: String,
    value: u8,
    selected_tens_digit: u8,
    ones_digit: u8,
}

impl ServerPercentileRoll {
    pub fn roll_id(&self) -> &str {
        &self.roll_id
    }

    pub const fn value(&self) -> u8 {
        self.value
    }

    pub const fn selected_tens_digit(&self) -> u8 {
        self.selected_tens_digit
    }

    pub const fn ones_digit(&self) -> u8 {
        self.ones_digit
    }
}

/// Opaque evidence for a d10 roll produced by the server OS CSPRNG.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct ServerD10Roll {
    roll_id: String,
    value: u8,
}

impl ServerD10Roll {
    pub fn roll_id(&self) -> &str {
        &self.roll_id
    }

    pub const fn value(&self) -> u8 {
        self.value
    }
}

/// Server-owned random evidence used by skill-improvement rules. A caller can
/// combine only opaque rolls that were generated by this module; domain and
/// persistence layers still validate whether the optional d10 is permitted.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct ServerGrowthRollEvidence {
    improvement_check: ServerPercentileRoll,
    increase: Option<ServerD10Roll>,
}

impl ServerGrowthRollEvidence {
    pub fn from_server_rolls(
        improvement_check: ServerPercentileRoll,
        increase: Option<ServerD10Roll>,
    ) -> Self {
        Self {
            improvement_check,
            increase,
        }
    }

    pub const fn improvement_check(&self) -> &ServerPercentileRoll {
        &self.improvement_check
    }

    pub const fn increase(&self) -> Option<&ServerD10Roll> {
        self.increase.as_ref()
    }
}

pub fn server_percentile_roll() -> KernelResult<ServerPercentileRoll> {
    let mut rng = OsRng;
    let selected_tens_digit = sample_decimal_digit(&mut rng);
    let ones_digit = sample_decimal_digit(&mut rng);
    let value = percentile_from_digits(selected_tens_digit, ones_digit)?;
    Ok(ServerPercentileRoll {
        roll_id: random_id("server_percentile", &mut rng),
        value,
        selected_tens_digit,
        ones_digit,
    })
}

pub fn server_d10_roll() -> ServerD10Roll {
    let mut rng = OsRng;
    ServerD10Roll {
        roll_id: random_id("server_d10", &mut rng),
        value: sample_decimal_digit(&mut rng) + 1,
    }
}

fn percentile_from_digits(tens_digit: u8, ones_digit: u8) -> KernelResult<u8> {
    if tens_digit > 9 || ones_digit > 9 {
        return Err(TrpgError::InvalidConfiguration("server_percentile_digit"));
    }
    let value = tens_digit * 10 + ones_digit;
    Ok(if value == 0 { 100 } else { value })
}

fn sample_decimal_digit(rng: &mut impl RngCore) -> u8 {
    const ACCEPT_BELOW: u32 = u32::MAX - (u32::MAX % 10);
    loop {
        let value = rng.next_u32();
        if value < ACCEPT_BELOW {
            return (value % 10) as u8;
        }
    }
}

fn random_id(prefix: &str, rng: &mut impl RngCore) -> String {
    let mut bytes = [0_u8; 16];
    rng.fill_bytes(&mut bytes);
    format!("{prefix}_{}", hex_encode(&bytes))
}

fn hex_encode(bytes: &[u8]) -> String {
    const HEX: &[u8; 16] = b"0123456789abcdef";
    let mut output = String::with_capacity(bytes.len() * 2);
    for byte in bytes {
        output.push(HEX[(byte >> 4) as usize] as char);
        output.push(HEX[(byte & 0x0f) as usize] as char);
    }
    output
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn server_roll_evidence_is_range_checked_and_distinct() {
        let percentile = server_percentile_roll().unwrap();
        let d10 = server_d10_roll();
        assert!((1..=100).contains(&percentile.value()));
        assert!((1..=10).contains(&d10.value()));
        assert_ne!(percentile.roll_id(), d10.roll_id());
    }
}
