// SPDX-License-Identifier: PolyForm-Noncommercial-1.0.0

package projectctl

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

// x-section-id: PROJECTCTL-GOVERNANCE-SOURCE
const generatedMarker = "<!-- DO NOT EDIT: generated by projectctl docs generate. -->"

const governanceSourceCommit = "9940a9ff18ac4b09d27d982d84a0703d3469c781"

const governanceSignerFingerprint = "SHA256:zR55HATrI3+mzVZW3uc8MsCxE+g5fyImXdD8X7WKkt4"

type generatedDocument struct {
	path string
	data []byte
}

func (a *App) docsCommand(args []string) error {
	if len(args) != 1 {
		return usageError("docs generate|check")
	}
	switch args[0] {
	case "generate":
		return a.generateDocuments()
	case "check":
		return a.checkDocuments()
	default:
		return usageError("docs generate|check")
	}
}

func (a *App) generatedDocuments() ([]generatedDocument, error) {
	decisions, requirements, tests, trace, err := a.loadAuthority()
	if err != nil {
		return nil, err
	}
	if err := validateDecisions(decisions); err != nil {
		return nil, err
	}
	if err := a.validateTraceability(decisions, requirements, tests, trace); err != nil {
		return nil, err
	}

	documents := []generatedDocument{
		{path: "docs/70-decisions/DECISION_INDEX.md", data: generateDecisionIndex(decisions)},
		{path: "docs/70-decisions/SUPERSESSION_MAP.md", data: generateSupersessionMap(decisions)},
		{path: "docs/90-traceability/TRACEABILITY.md", data: generateTraceabilityIndex(requirements, tests, trace)},
	}
	if _, statErr := os.Stat(filepath.Join(a.root, ".codex", "state")); statErr == nil {
		documents = append(documents, generatedDocument{path: ".codex/state/DECISION_DIGEST.md", data: generateDecisionDigest(decisions)})
	}
	return documents, nil
}

func (a *App) generateDocuments() error {
	documents, err := a.generatedDocuments()
	if err != nil {
		return err
	}
	for _, document := range documents {
		if err := atomicWrite(filepath.Join(a.root, filepath.FromSlash(document.path)), document.data, 0o644); err != nil {
			return fmt.Errorf("write %s: %w", document.path, err)
		}
		fmt.Fprintf(a.stdout, "[GENERATED] %s\n", document.path)
	}
	return nil
}

func (a *App) checkDocuments() error {
	documents, err := a.generatedDocuments()
	if err != nil {
		return err
	}
	var drift []string
	for _, document := range documents {
		actual, readErr := os.ReadFile(filepath.Join(a.root, filepath.FromSlash(document.path)))
		if readErr != nil || !bytes.Equal(actual, document.data) {
			drift = append(drift, document.path)
		}
	}
	if len(drift) != 0 {
		return fmt.Errorf("generated documentation drift: %s; run projectctl docs generate", strings.Join(drift, ", "))
	}
	fmt.Fprintln(a.stdout, "[PASS] generated documentation is current")
	return nil
}

func atomicWrite(path string, data []byte, mode os.FileMode) error {
	temporary, err := os.CreateTemp(filepath.Dir(path), ".projectctl-generated-*")
	if err != nil {
		return err
	}
	temporaryName := temporary.Name()
	defer os.Remove(temporaryName)
	if err := temporary.Chmod(mode); err != nil {
		temporary.Close()
		return err
	}
	if _, err := temporary.Write(data); err != nil {
		temporary.Close()
		return err
	}
	if err := temporary.Close(); err != nil {
		return err
	}
	return os.Rename(temporaryName, path)
}

// x-section-id: PROJECTCTL-DECISION-GENERATOR
func generateDecisionIndex(register decisionRegister) []byte {
	var output strings.Builder
	output.WriteString("---\ndocument_id: DECISION-INDEX\nauthority: generated-reference\nstatus: ACTIVE\nsource: DECISION_REGISTER.yaml\n---\n\n")
	fmt.Fprintf(&output, "%s\n\n# %s 决策索引\n\n", generatedMarker, cleanInline(strings.TrimPrefix(register.BaselineID, "TRPG-PLATFORM-")))
	output.WriteString("> 权威机器来源为 `DECISION_REGISTER.yaml`。\n\n")

	statusCounts := map[string]int{}
	for _, item := range register.Decisions {
		statusCounts[item.Status]++
	}
	fmt.Fprintf(&output, "- 决策总数：**%d**\n", len(register.Decisions))
	fmt.Fprintf(&output, "- ACTIVE：**%d**\n", statusCounts["ACTIVE"])
	fmt.Fprintf(&output, "- SUPERSEDED：**%d**\n", statusCounts["SUPERSEDED"])
	fmt.Fprintf(&output, "- 基线状态：**%s**\n", cleanInline(register.BaselineStatus))
	fmt.Fprintf(&output, "- 权威语言：%s\n", cleanInline(register.AuthoritativeLanguage))

	stageOrder := make([]string, 0)
	byStage := map[string][]decision{}
	for _, item := range register.Decisions {
		if _, exists := byStage[item.SourceStage]; !exists {
			stageOrder = append(stageOrder, item.SourceStage)
		}
		byStage[item.SourceStage] = append(byStage[item.SourceStage], item)
	}
	for _, stage := range stageOrder {
		fmt.Fprintf(&output, "\n## %s\n\n", cleanInline(stage))
		output.WriteString("| 决策 ID | 状态 | 标题 | 范围 | 结论 |\n|---|---|---|---|---|\n")
		for _, item := range byStage[stage] {
			fmt.Fprintf(&output, "| `%s` | `%s` | %s | `%s` | %s |\n",
				cleanInline(item.ID), cleanInline(item.Status), cleanInline(item.Title),
				cleanInline(item.Scope), cleanInline(item.Statement))
		}
	}
	return []byte(output.String())
}

func generateSupersessionMap(register decisionRegister) []byte {
	var output strings.Builder
	output.WriteString("---\ndocument_id: SUPERSESSION-MAP\nauthority: generated-reference\nstatus: ACTIVE\nsource: DECISION_REGISTER.yaml\n---\n\n")
	output.WriteString(generatedMarker + "\n\n# 决策覆盖、例外与细化映射\n\n")
	output.WriteString("机器登记中的 `relationship_type` 是权威分类；只有 `SUPERSEDES` 会把登记内目标标记为 `SUPERSEDED`。\n\n")
	output.WriteString("| 关系类型 | 原对象 | 后续决策 | 影响 |\n|---|---|---|---|\n")
	for _, relation := range register.Supersessions {
		fmt.Fprintf(&output, "| `%s` | `%s` | `%s` | %s |\n",
			cleanInline(relation.RelationshipType), cleanInline(relation.Superseded),
			cleanInline(relation.SupersededBy), cleanInline(relation.Effect))
	}
	output.WriteString("\n## 适用原则\n\n")
	output.WriteString("1. 更晚且更具体的决策可形成领域例外，不自动推翻全平台原则。\n")
	output.WriteString("2. `R8-A13` 已被官方桌游后续设计完整替代，因此状态为 `SUPERSEDED`。\n")
	output.WriteString("3. `R6-A06` 保持全局有效，`R11-A12` 只对官方隐藏信息桌游高难度 AI 形成例外。\n")
	output.WriteString("4. `R4-A11` 的无普通观察者原则保持有效，死亡后/淘汰后只读状态是窄例外。\n")
	output.WriteString("5. `R12-A08` 只改变浏览器本地模型的交付版本，不删除 R5 的长期设计。\n")
	output.WriteString("6. `R13-A04` 是旧代码处理的最终规则：零迁移。\n")
	output.WriteString("7. `R24-A08` 的全局 55%/70% 预算已由 R25 部分覆盖；只有 enforcement-enabled profile 执行 ratio gate。\n")
	return []byte(output.String())
}

func generateTraceabilityIndex(requirements requirementsDocument, tests testCatalog, trace traceabilityDocument) []byte {
	testsByID := make(map[string]testCase, len(tests.Tests))
	for _, item := range tests.Tests {
		testsByID[item.ID] = item
	}
	mappings := make(map[string]traceMapping, len(trace.Mappings))
	for _, item := range trace.Mappings {
		mappings[item.RequirementID] = item
	}

	var output strings.Builder
	output.WriteString("---\ndocument_id: TRACEABILITY-INDEX\nauthority: generated-reference\nstatus: ACTIVE\nsource:\n- REQUIREMENTS.yaml\n- TEST_CATALOG.yaml\n- TRACEABILITY.yaml\n---\n\n")
	output.WriteString(generatedMarker + "\n\n# 需求—规范—测试追踪索引\n\n")
	fmt.Fprintf(&output, "- 要求：%d\n- 计划测试：%d\n\n", len(requirements.Requirements), len(tests.Tests))
	output.WriteString("| 要求 | 标题 | 规范 | 里程碑 | 测试 | 状态 |\n|---|---|---|---|---|---|\n")
	for _, requirement := range requirements.Requirements {
		mapping := mappings[requirement.ID]
		testLabels := make([]string, 0, len(mapping.TestIDs))
		for _, id := range mapping.TestIDs {
			if _, exists := testsByID[id]; exists {
				testLabels = append(testLabels, "`"+cleanInline(id)+"`")
			}
		}
		fmt.Fprintf(&output, "| `%s` | %s | `%s` | `%s` | %s | `%s` |\n",
			cleanInline(requirement.ID), cleanInline(requirement.Title), cleanInline(mapping.OwningSpec),
			cleanInline(mapping.Milestone), strings.Join(testLabels, "<br>"), cleanInline(mapping.ImplementationStatus))
	}
	return []byte(output.String())
}

func generateDecisionDigest(register decisionRegister) []byte {
	selected := map[string]bool{
		"R13-A04": true,
		"R21-A01": true, "R21-A03": true, "R21-A05": true, "R21-A06": true, "R21-A07": true, "R21-A14": true, "R21-A15": true,
		"R22-A03": true, "R22-A05": true, "R22-A06": true, "R22-A15": true, "R22-A16": true,
		"R23-A01": true, "R23-A03": true, "R23-A08": true, "R23-A11": true, "R23-A12": true, "R23-A13": true,
		"R24-A01": true, "R24-A05": true, "R24-A06": true, "R24-A08": true, "R24-A09": true, "R24-A12": true, "R24-A13": true, "R24-A14": true, "R24-A15": true,
		"R25-A01": true, "R25-A02": true, "R25-A03": true, "R25-A04": true,
		"R26-A01": true, "R26-A02": true, "R26-A03": true, "R26-A04": true,
	}
	var output strings.Builder
	output.WriteString("---\ndocument_id: CODEX-DECISION-DIGEST\nschema_version: 1\ndocument_kind: state-summary\nauthority: state-summary\nstatus: ACTIVE\n")
	fmt.Fprintf(&output, "source_commit: %q\n", governanceSourceCommit)
	output.WriteString("---\n\n" + generatedMarker + "\n\n# 有效决策摘要\n\n")
	output.WriteString("本摘要只列 M0 与当前 Codex/governance-maintenance 路由常用决策；冲突时返回 `docs/70-decisions/DECISION_REGISTER.yaml` 和主题规范。\n\n")
	output.WriteString("| 决策 ID | 状态 | 标题 | 结论 |\n|---|---|---|---|\n")
	count := 0
	for _, item := range register.Decisions {
		if !selected[item.ID] {
			continue
		}
		fmt.Fprintf(&output, "| `%s` | `%s` | %s | %s |\n", cleanInline(item.ID), cleanInline(item.Status), cleanInline(item.Title), cleanInline(item.Statement))
		count++
	}
	fmt.Fprintf(&output, "\n- 摘要条目：%d\n- 机器登记总数：%d\n", count, len(register.Decisions))
	return []byte(output.String())
}

func sortedKeys[V any](values map[string]V) []string {
	keys := make([]string, 0, len(values))
	for key := range values {
		keys = append(keys, key)
	}
	sort.Strings(keys)
	return keys
}
