bind 0.0.0.0
protected-mode yes
port 0
tls-port 6379
tls-cert-file /run/secrets/redis_tls_certificate
tls-key-file /run/secrets/redis_tls_private_key
tls-ca-cert-file /run/secrets/redis_tls_ca_certificate
tls-auth-clients yes
aclfile /run/secrets/redis_acl
appendonly yes
dir /data
